config/routes.rb
Bueller::Application.routes.draw do
  resources :students
  resources :sessions
  resources :attendances
  root to: "welcome#index"
  match '/signup',  to: 'sessions#index',       via: 'post'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/attendances', to: 'attendances#new',  via: 'post'
  match '/attendances/show', to: 'attendances#index', via: 'get' 
  match 'list', to: 'students#list', via: 'get'
  match "/" , to: 'welcome#index', via: 'post' 
end

app/models/student.rb
class Student < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  has_many :attendances
  has_secure_password
  validates_presence_of :password, :on => :create
  
  def Student.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Student.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def self.last_attendance( student )
    Attendance.where(:student_id => student.id ).last || Attendance.new 
  end
  
  def self.in_seat(seat, now=Date.today)
    present(now).where('attendances.seat = ?', seat)
  end

  def self.absent(now=Date.today)
    where.not(id: present(now))
  end

  def self.present(now=Date.today)
    joins(:attendances).where(attendances: {attended_on: now})
  end

  private

    def create_remember_token
      self.remember_token = Student.encrypt(Student.new_remember_token)
    end
end

app/controllers/students_controller.rb
require 'open-uri'
require 'digest/md5'

class StudentsController < ApplicationController
  
  skip_before_filter :require_login
  
  def new
    
  end
  
  def list
    @students = Student.all
  end
  
  def show
    
    @list = Attendance.where(:student_id => params[:id].to_i ) 
    @student = Student.find( params[:id] )
    
  end
  
  def index
    @student =  Student.new
  end
  
  def create
    
    @student = Student.create(params[:student].permit(:name, :nickname, :email, :imageurl, :password, :password_confirmation)  )
        
     
    if @student.imageurl.empty?
      email_address = @student.email.downcase
      hash = Digest::MD5.hexdigest(email_address)
      File.write("/home/action/nku-rails/app/assets/images/"+Student.count.to_s+".jpg", open( "http://www.gravatar.com/avatar/#{hash}"
                                                                                           ).read, {mode: 'wb'})
    else
      
      File.write("/home/action/nku-rails/app/assets/images/"+Student.count.to_s+".jpg", open( @student.imageurl.to_s ).read, {mode: 'wb'})
    
    end
    @student.imageurl =Student.count.to_s
    
    if @student.save
      session[:user_id] = @student.id
      flash[:notice] = " the student was successfully created."
      redirect_to :root
    else 
      render 'index'
    end  
  end
  
  def edit
    @student=Student.find(session[:user_id])
  end
  
  def test
  end
  
  def update
    @student = Student.find(params[:id])
    @tempImagePath  = @student.imageurl
    @student.update(params[:student].permit(:name, :nickname, :email, :imageurl, :password, :password_confirmation))
    
    if( @student.imageurl.eql? "Delete")
      
      @student.imageurl = "default"
      
    elsif( @student.imageurl.eql?  "Change")
      
          if params[:new_image_url].empty?
            email_address = @student.email.downcase
            hash = Digest::MD5.hexdigest(email_address)
            File.write("/home/action/nku-rails/app/assets/images/"+Student.count.to_s+".jpg", 
                    open( "http://www.gravatar.com/avatar/#{hash}").read, {mode: 'wb'})
          else
            File.write("/home/action/nku-rails/app/assets/images/"+Student.count.to_s+".jpg", 
                    open( params[:new_image_url] ).read, {mode: 'wb'})
   
          end
          @student.imageurl =Student.count.to_s  
    else
      @student.imageurl = @tempImagePath  
    end

    if @student.save
      redirect_to :root, :notice => "You successfully updated your profile. !"
    else
      render 'edit'
    end
  end

  
  private
  def post_params
    params.require(:student).permit(:name, :nickname, :email, :imageurl, :password, :password_confirmation)  
  end
  
end

app/views/students/edit.html.erb
<h1>Editing Student</h1>
<ul>
  <% for message in @student.errors.full_messages %>
    <li><%= message %></li>
  <% end %>
</ul> 

<%= form_for :student, url: student_path(current_user), method: :patch do |f| %>


  
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :nickname %><br>
    <%= f.text_area :nickname %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </p>

  <p>
    <%= label_tag :new_image_url %><br>
    <%= text_area_tag :new_image_url %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </p>

  <p>
    <%= image_tag @student.imageurl+".jpg" , :width => 80, :height => 80 %></br>
    
    <%= f.radio_button :imageurl, 'Keep' %> Keep the existing picture</br>
    <%= f.radio_button :imageurl, 'Change' %> Change the existing picture</br>
    <%= f.radio_button :imageurl, 'Delete' %> Delete the existing picture</br>

  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/students/index.html.erb
<h1>New Student</h1>
      <ul>
          <% for message in @student.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    

<%= form_for :student do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :imageurl %><br>
    <%= f.text_field :imageurl %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/students/list.html.erb
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Nick Name</th>
    <th>Email</th>
    <th>Avatar</th>
  </tr>
  <tbody>
  <% @students.each do |s| %>
  <tr>
    <td><%= s.name %>
    <td><%= s.nickname %></td>
    <td><%= s.email %></td>
    <td><%= image_tag s.imageurl.to_s+".jpg" , :width => 50, :height => 50 %></td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/students/new.html.erb
<h1>New New Student</h1>
      <ul>
          <% for message in @student.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    

<%= form_for :student do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :imageurl %><br>
    <%= f.text_field :imageurl %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/students/show.html.erb
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Attendance Date</th>
    <th>Seat</th>
  </tr>
  <tbody>
  <% @list.each do |a| %>
  <tr>
    <td><%= @student.name %>
    <td><%= a.attended_on %></td>
    <td><%= a.seat %></td>
  </tr>
  <% end %>
  </tbody>
</table>