config/routes.rb
Bueller::Application.routes.draw do
  resources :students
  resources :sessions
  resources :attendances
  root to: "welcome#index"
  match '/signup',  to: 'sessions#index',       via: 'post'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/attendances', to: 'attendances#new',  via: 'post'
  match '/attendances/show', to: 'attendances#index', via: 'get' 
  match 'list', to: 'students#list', via: 'get'
  match "/" , to: 'welcome#index', via: 'post' 
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= render 'layouts/messages' %>
    </div>
    <div class="collapse navbar-collapse">
      <% if !current_user.nil? %>
        <%= link_to 'Home', root_path, class: 'navbar-brand' -%>&nbsp;&nbsp;
        <%= link_to 'Student list', list_path -%>&nbsp;&nbsp;
        <%= link_to 'Attendance History', attendances_show_path %>&nbsp;&nbsp;
        <%= link_to "Sign out", signout_path, method: "delete" -%>&nbsp;&nbsp;
        <%= link_to 'Edit', edit_student_path(current_user) -%>&nbsp;&nbsp;
        <%= link_to 'I&#39m Here'.html_safe, controller: "attendances"%>
      <% end %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Bueller" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Bueller" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
    <script src="//code.jquery.com/jquery-1.9.1.js"></script>
    <script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script>
      $(function() {
        $( "#datepicker" ).datepicker();
      });
  </script>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= yield %>
    </main>
  </body>
</html>